import logging

from ._uc_capabilities import UCCapabilities, get_uc_capabilities
from .contract_bundle import ContractBundle, governance_check, governance_preview, load_contract_bundle
from .contract_schema import yaml_schema
from .governance import (
    AccessContract,
    AccessGrant,
    AnnotationsContract,
    ColumnAnnotations,
    ColumnMask,
    OperationsContract,
    PiiAnnotation,
    RowFilter,
    TableAnnotations,
    access_drift_report,
    governance_referenced_columns,
    validate_governance_contract,
)
from .hooks import IngestionHooks
from .maintenance import apply_ctrl_retention, build_ctrl_retention_plan
from .bundles import (
    apply_access_bundle,
    apply_annotations_bundle,
    apply_governance_bundle,
    ingest_bundle,
)
from .ingestion import (
    FrameworkConfig,
    QualityExpression,
    ConnectorSpec,
    DeduplicateConfig,
    ExecutionCatchupConfig,
    ExecutionConfig,
    ExecutionWindow,
    ExecutionWindowConfig,
    IngestionPlan,
    QualityRules,
    SourceSpec,
    TransformConfig,
    ingest,
    ingest_plan,
    validate_plan_shape,
)
from .streaming import ingest_stream_plan
from .sources import (
    ConnectorCapabilities,
    HttpFileConnector,
    SourceResolution,
    diagnose_source_connectors,
    get_source_resolver,
    list_source_connector_details,
    list_source_resolvers,
    redact_secrets,
    redact_text,
    register_source_resolver,
    resolve_batch_source,
    resolve_secrets,
    source_connector_details,
)
from .templates import (
    contract_template_details,
    contract_template_files,
    get_contract_template,
    list_contract_templates,
    recommend_contract_templates,
)
from .presets import apply_preset, get_preset, list_presets, preset_details, register_preset
from .plan import target_full_table_name, target_schema_name
from .shape import (
    ShapeArrayConfig,
    ShapeColumnConfig,
    ShapeConfig,
    ShapeFlattenConfig,
    ShapeJsonConfig,
    ShapeZipArraysConfig,
    apply_shape,
)
from .writers import register_write_mode
from .quality import register_quality_rule

__all__ = [
    "FrameworkConfig",
    "AccessContract",
    "AccessGrant",
    "ConnectorCapabilities",
    "ConnectorSpec",
    "contract_template_details",
    "contract_template_files",
    "DeduplicateConfig",
    "ExecutionCatchupConfig",
    "ExecutionConfig",
    "ExecutionWindow",
    "ExecutionWindowConfig",
    "UCCapabilities",
    "access_drift_report",
    "AnnotationsContract",
    "ColumnAnnotations",
    "ColumnMask",
    "ContractBundle",
    "IngestionHooks",
    "HttpFileConnector",
    "OperationsContract",
    "PiiAnnotation",
    "QualityExpression",
    "IngestionPlan",
    "QualityRules",
    "RowFilter",
    "SourceSpec",
    "SourceResolution",
    "ShapeArrayConfig",
    "ShapeColumnConfig",
    "ShapeConfig",
    "ShapeFlattenConfig",
    "ShapeJsonConfig",
    "ShapeZipArraysConfig",
    "TableAnnotations",
    "TransformConfig",
    "diagnose_source_connectors",
    "get_source_resolver",
    "get_uc_capabilities",
    "governance_check",
    "governance_preview",
    "governance_referenced_columns",
    "apply_access_bundle",
    "apply_annotations_bundle",
    "apply_ctrl_retention",
    "apply_governance_bundle",
    "build_ctrl_retention_plan",
    "ingest",
    "ingest_bundle",
    "ingest_plan",
    "ingest_stream_plan",
    "load_contract_bundle",
    "apply_preset",
    "apply_shape",
    "get_preset",
    "get_contract_template",
    "list_presets",
    "list_contract_templates",
    "list_source_connector_details",
    "list_source_resolvers",
    "preset_details",
    "register_preset",
    "register_source_resolver",
    "recommend_contract_templates",
    "redact_secrets",
    "redact_text",
    "resolve_batch_source",
    "resolve_secrets",
    "source_connector_details",
    "target_full_table_name",
    "target_schema_name",
    "register_write_mode",
    "register_quality_rule",
    "validate_plan_shape",
    "validate_governance_contract",
    "yaml_schema",
]

logging.getLogger(__name__).addHandler(logging.NullHandler())

__version__ = "2.10.0"
